### ISSUE TITLE
Test the documentation generation from swaggerhub

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api-service#1]
The need is to have a generic documentation for all the PDS API service implementation. Independantly from the different implementation which will also embed the documentation.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I tested documentation generation from the swaggerhub integration side.

3 proposed outputs:
https://nasa-pds.github.io/pds-api/html/
https://nasa-pds.github.io/pds-api/html2/
https://nasa-pds.github.io/pds-api/dynamic-html/docs/

This was very quick to setup. Although none of them look very nice in my opinion. Is there one you would like us to keep updated on the pds-api repo gh-pages ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl wow. they surprisingly all look pretty bad. maybe we just use the pds-api documentation endpoint for the specification, and we then forward to specific parts of the actual API endpoint for explicit examples / information since that looks way nicer and is more fully functional.

thoughts?

**Comment by tloubrieu-jpl** [comment]
Delayed: None of the default documentation output looks nice. This requires more work to have an acceptable documentation site.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I have this documentation generated through github action. It looks better I think. It is the same as the one used by OSTI, but I think I've seen that at some other places before: https://nasa-pds.github.io/pds-api/

**Comment by jordanpadams** [comment]
@tloubrieu-jpl 👍  looks good for now. eventually we will need to style / sync up all our docs, but we can make that a part of @edwardbarraza's documentation overhaul coming later this year / early next year

**Comment by tloubrieu-jpl** [comment]
Yes, I was thinking we will need the styling part with logo and everything. That would be good if Edward can have a look at that since we want the API to be visible as a PDS interface. I create a ticket the for styling.
